### ISSUE TITLE
Plans / Roadmap

### ISSUE THREAD

**Issue by krateng** [krateng/maloja#96]
Using this issue as makeshift todo list

- [ ] Fully customizable regex rules
- [ ] globalconf should eventually read directory settings normally (respecting default)
- [ ] Jinja: refactoring imports and includes
- [ ] Visual indicator for associated artists' scrobbles in scrobble bars
- [ ] Import directly from Last.fm (and others) instead of having to download a file
- [ ] Move to a proper database (SQLite, ZODB?)

**Comment by FoxxMD** [comment]
For scrobble forwarding -- not exactly a solution for maloja per se but I could easily implement forwarding for [multi-scrobbler](https://github.com/FoxxMD/multi-scrobbler). I already have this implemented for last.fm (last.fm -> maloja) so it would be trivial to reverse it or allow forwarding to multiple/arbitrary other maloja servers.

**Comment by northys** [comment]
> arm64 docker build

docker [supports building xplatform images by default using qemu](https://docs.docker.com/buildx/working-with-buildx/) and it is ridiculously slow. it looks like your `Containerfile` is already buildable on arm platform. i tried to build it on my raspberry and it succeeded (it's actually still running but i see no reason why it should fail).

if you want i may try to take care of it. i'm curious how to do that. also, that would be my first time doing something with github actions and i want learn something new :)

**Comment by krateng** [comment]
I'd be very grateful!

**Comment by mariolopjr** [comment]
@krateng taking a look at the roadmap, it would be nice to have album support. Data-wise, it looks like albums are (temporarily?) stored in the `extra` column of each scrobble. In planning this work, I was thinking of first opening a PR to write a migration to extract the album from the `extra` and dump them into a new album table, with a pivot table of `trackalbum` (and clean up the old data).

Do you prefer small PRs that build functionality or open a PR with the first step and keep that PR open until the entire feature is complete?

**Comment by krateng** [comment]
I appreciate the enthusiasm, but I'd like to implement core database changes myself since it would be more work to thoroughly review a PR than write the code. If you'd like to build the overview page, you could first build it with the data available - additional parts can always be added later.

**Comment by mariolopjr** [comment]
@krateng sounds good no worries! I'll take a look at expanding the current web, as well as working on at #97 as well. :)

**Comment by timkicker** [comment]
i think albums should be a priority. but i guess that'd mean an enormous restructure of the application?

**Comment by darknesswithsorrowtears** [comment]
I believe that albums are necessary for complete listening statistics, it would be great to see their support

**Comment by FoxxMD** [comment]
I'd personally like to see "Fix threading" make it into 3.2 or the near future to help address #177 and #54 -- for users who use older CPUs in our servers and particularly for ARM (raspberry pi) setups it makes browsing the UI painful. 

I love that Maloja ingests all my history but I avoid using the UI because it takes 10-30 seconds to navigate to any page using the Xenon E5-2650L v2 (1.70ghz 10 core) in my server. This is the same server that has no issue handling Plex browsing 1000's of movies, nextcloud, grafana/influx with years of time-series data, and several other self-hosted websites that are speedy in navigating thousands of resources.

**Comment by krateng** [comment]
Alright, I now have very experimental album support.

If anyone wants to try it and give some feedback, check out the branch https://github.com/krateng/maloja/tree/feature-albums. Make sure to backup your data first!

Right now, maloja accepts album information from new scrobbles; and you can try to parse old scrobbles with the command `maloja parsealbums`. You can also do the usual web interface stuff like merging and renaming.

**Comment by duckfromdiscord** [comment]
I see genres under "Considered". Perhaps genres could be done thru something like everynoise and/or the Spotify API powering it?
